config/routes.rb
Rails.application.routes.draw do

  get '/contacts', to: 'contacts#index', as: :contacts

  get '/contacts/new', to: 'contacts#new', as: :new

  post '/contacts', to: 'contacts#create'

  get '/contacts/:id', to: 'contacts#show', as: :show

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def index
		@contacts = Contact.order(name: :asc)
		render 'index'
	end
	def new
	end
	def create
		# Create new Contact from params[:contact]
		contact = Contact.new(
			:name => params[:contact][:name],
			:address => params[:contact][:address],
			:phone => params[:contact][:phone],
			:email => params[:contact][:email]
			)
		if !contact[:name].blank? and !contact[:address].blank?
			contact.save
			redirect_to("/contacts")
		else
			flash[:alert] = "Please fill out the name and address of the contact"
			render '/contacts/new'	
		end
		# Render contact's attributes
		# render(:text => contact.attributes)
		
	end
	def show
		contact_id = params[:id]
		@contact = Contact.find_by(id: contact_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/index.html.erb
<ul>
	<% @contacts.each do | contact | %>
		<li>
			<%= link_to contact.name, show_path(contact) %>
			<%= contact.address %>
			<%= contact.phone %>
			<%= contact.email %>
		</li>
	<% end %>
</ul>

<%= link_to 'Add a new contact', new_path %>

app/views/contacts/new.html.erb
<% if flash[:alert] %>
  <%= flash[:alert] %>
<%end%>

<h1>Add a new contact</h1>

<form action="/contacts" method="POST"> 
  <div>
    <label for="contact_name">Name*</label>
    <input type="text" name="contact[name]" id="contact_name">
  </div>

  <div>
    <label for="contact_address">Address*</label>
    <textarea name="contact[address]" id="contact_address"></textarea>
  </div>

  <div>
    <label for="contact_phone">Phone number</label>
    <input type="tel" name="contact[phone]" id="contact_phone">
  </div>

  <div>
    <label for="contact_email">Email</label>
    <input type="email" name="contact[email]" id="contact_email">
  </div>
  <button type="submit">Add this contact</button>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
</form>

app/views/contacts/show.html.erb
<%= @contact.name %>
<%= @contact.address %>
<%= @contact.phone %>
<%= @contact.email %>

<%= link_to 'Return to contact\'s page', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Adressbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>